---
name: Pairdrop
version: 1.10.11
slug: pairdrop
description: Share files between any device securely and locally
url: https://github.com/wrouesnel/addon-pairdrop
codenotary: wrouesnel@wrouesnel.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services: []
hassio_api: true
backup_exclude:
  - "*/logs"
options:
  websocket_fallback: false
  rtc_config_sdpSemantics: unified-plan
  rtc_config_iceServers:
    - urls: "stun:stun.l.google.com:19302"
schema:
  websocket_fallback: bool
  rtc_config_sdpSemantics: str
  rtc_config_iceServers:
  - urls: str
    username: str?
    credential: str?
