---
name: Pairdrop
version: 1.11.4
slug: pairdrop
description: Share files between any device securely and locally
url: https://github.com/gunsha/addon-pairdrop
codenotary: gonzaller@gmail.com
webui: http://[HOST]:[PORT:3000]
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services: []
hassio_api: true
backup_exclude:
  - "*/logs"
options:
  websocket_fallback: false
  rtc_config_sdpSemantics: unified-plan
  rtc_config_iceServers:
    - urls: "stun:stun.l.google.com:19302"
ports:
  3000/tcp: 3000
schema:
  websocket_fallback: bool
  rtc_config_sdpSemantics: str
  rtc_config_iceServers:
  - urls: str
    username: str?
    credential: str?
